### ISSUE TITLE
Dark glass does not work

### ISSUE THREAD

**Issue by DeleteMetaInf** [inzhefop/extrautilitiesreborn#2]
Dark glass and its variant do not block light.

![2022-10-07_09 43 59](https://user-images.githubusercontent.com/59761487/194500081-465f321f-8048-48f3-a177-c3616aee91f3.png)

### Versions
* **Minecraft:** 1.18.2
* **Forge:**  40.1.80 (latest)
* **Extra Utilities Reborn:** 1.7.1

**Comment by inzhefop** [comment]
should be fixed in release 1.7.3
![2022-10-07_12 52 35](https://user-images.githubusercontent.com/76850445/194537310-b02f5cfa-bd94-4917-83ba-680a8077be78.png)
