### ISSUE TITLE
Ender-Thermic Pump Unable to detect Fence boundary

### ISSUE THREAD

**Issue by Degus22** [inzhefop/extrautilitiesreborn#4]
I tried to place and use the Ender-Thermic Pump but got an error in the chat:
![grafik](https://user-images.githubusercontent.com/52410669/195110894-40776e39-af94-4a71-b5b8-b25ffcc61699.png)
Is it not implemented yet or am I doing something wrong?
Do you I need to use Ender Marker for the Pump too?

**Comment by Degus22** [comment]
![grafik](https://user-images.githubusercontent.com/52410669/195113519-85324c1f-3bfa-4df8-baa3-fe1043dafe24.png)
doesnt work with markers either :/

**Comment by inzhefop** [comment]
![2022-10-11_18 13 47](https://user-images.githubusercontent.com/76850445/195144957-dec3c52f-5536-465b-983b-e550f2edc090.png)
Have you right clicked the marker? The Marker stores the information about the area [An activated marker has this little particles over it]. Then place the Ender Quarry/Pump next to the marker and rigt click it, too. Then it should work.
