### ISSUE TITLE
I shouldn't post these things when I'm frustrated

### ISSUE THREAD

**Issue by suneyedset** [inzhefop/extrautilitiesreborn#5]
The advanced chicken wing ring took a lot of effort to make. How is it different from the regular chicken wing ring exactly? No offense, but There's not much explanation so far in terms of documentation, and yes, I appreciate it's a work in progress. It did seem a little like I was making your mod's equivalence of an angel ring, but it doesn't seem different from the base chicken wing ring at all. At least it could maybe eliminate fall damage?

**Comment by inzhefop** [comment]
In the newest version fall dmg is disabled when you have the advanced ring in inventory
